export const FLEXOKI_CSS_TEMPLATE = `/* flexoki.css - generated by flexoki-mcp-server */
:root {
  color-scheme: light dark;

  --fl-black: #100F0F;
  --fl-paper: #FFFCF0;
  --fl-base-950: #1C1B1A;
  --fl-base-900: #282726;
  --fl-base-850: #343331;
  --fl-base-800: #403E3C;
  --fl-base-700: #575653;
  --fl-base-600: #6F6E69;
  --fl-base-500: #878580;
  --fl-base-300: #B7B5AC;
  --fl-base-200: #CECDC3;
  --fl-base-150: #DAD8CE;
  --fl-base-100: #E6E4D9;
  --fl-base-50: #F2F0E5;

  --fl-red-600: #AF3029; --fl-red-400: #D14D41;
  --fl-or-600: #BC5215; --fl-or-400: #DA702C;
  --fl-ye-600: #AD8301; --fl-ye-400: #D0A215;
  --fl-gr-600: #66800B; --fl-gr-400: #879A39;
  --fl-cy-600: #24837B; --fl-cy-400: #3AA99F;
  --fl-bl-600: #205EA6; --fl-bl-400: #4385BE;
  --fl-pu-600: #5E409D; --fl-pu-400: #8B7EC8;
  --fl-ma-600: #A02F6F; --fl-ma-400: #CE5D97;
}

:root,
[data-theme="light"] {
  color-scheme: light;

  --fl-bg: #FFFCF0;
  --fl-bg-2: #F2F0E5;
  --fl-ui: #E6E4D9;
  --fl-ui-2: #DAD8CE;
  --fl-ui-3: #CECDC3;

  --fl-tx: #100F0F;
  --fl-tx-2: #6F6E69;
  --fl-tx-3: #B7B5AC;

  --fl-re: #AF3029;
  --fl-or: #BC5215;
  --fl-ye: #AD8301;
  --fl-gr: #66800B;
  --fl-cy: #24837B;
  --fl-bl: #205EA6;
  --fl-pu: #5E409D;
  --fl-ma: #A02F6F;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
    color-scheme: dark;

    --fl-bg: #100F0F;
    --fl-bg-2: #1C1B1A;
    --fl-ui: #282726;
    --fl-ui-2: #343331;
    --fl-ui-3: #403E3C;

    --fl-tx: #CECDC3;
    --fl-tx-2: #878580;
    --fl-tx-3: #575653;

    --fl-re: #D14D41;
    --fl-or: #DA702C;
    --fl-ye: #D0A215;
    --fl-gr: #879A39;
    --fl-cy: #3AA99F;
    --fl-bl: #4385BE;
    --fl-pu: #8B7EC8;
    --fl-ma: #CE5D97;
  }
}

[data-theme="dark"] {
  color-scheme: dark;

  --fl-bg: #100F0F;
  --fl-bg-2: #1C1B1A;
  --fl-ui: #282726;
  --fl-ui-2: #343331;
  --fl-ui-3: #403E3C;

  --fl-tx: #CECDC3;
  --fl-tx-2: #878580;
  --fl-tx-3: #575653;

  --fl-re: #D14D41;
  --fl-or: #DA702C;
  --fl-ye: #D0A215;
  --fl-gr: #879A39;
  --fl-cy: #3AA99F;
  --fl-bl: #4385BE;
  --fl-pu: #8B7EC8;
  --fl-ma: #CE5D97;
}
`;

export const FLEXOKI_THEME_JS_TEMPLATE = `/** flexoki-theme.js - generated by flexoki-mcp-server */
const flexokiColors = {
  black: '#100F0F',
  paper: '#FFFCF0',
  base: {
    950: '#1C1B1A',
    900: '#282726',
    850: '#343331',
    800: '#403E3C',
    700: '#575653',
    600: '#6F6E69',
    500: '#878580',
    300: '#B7B5AC',
    200: '#CECDC3',
    150: '#DAD8CE',
    100: '#E6E4D9',
    50: '#F2F0E5',
  },
  red: { DEFAULT: '#AF3029', light: '#D14D41' },
  orange: { DEFAULT: '#BC5215', light: '#DA702C' },
  yellow: { DEFAULT: '#AD8301', light: '#D0A215' },
  green: { DEFAULT: '#66800B', light: '#879A39' },
  cyan: { DEFAULT: '#24837B', light: '#3AA99F' },
  blue: { DEFAULT: '#205EA6', light: '#4385BE' },
  purple: { DEFAULT: '#5E409D', light: '#8B7EC8' },
  magenta: { DEFAULT: '#A02F6F', light: '#CE5D97' },
  bg: 'var(--fl-bg)',
  bg2: 'var(--fl-bg-2)',
  ui: 'var(--fl-ui)',
  tx: 'var(--fl-tx)',
  tx2: 'var(--fl-tx-2)',
  cy: 'var(--fl-cy)',
  re: 'var(--fl-re)',
  gr: 'var(--fl-gr)',
  bl: 'var(--fl-bl)',
};

const flexokiTheme = {
  colors: {
    flexoki: flexokiColors,
  },
};

module.exports = { flexokiColors, flexokiTheme };
`;

export const THEME_TOGGLE_JS_TEMPLATE = `/** theme-toggle.js - generated by flexoki-mcp-server */
(function () {
  'use strict';

  const root = document.documentElement;
  const toggle = document.getElementById('theme-toggle');
  const media = window.matchMedia('(prefers-color-scheme: dark)');
  let current = media.matches ? 'dark' : 'light';

  root.setAttribute('data-theme', current);
  sync();

  media.addEventListener('change', (event) => {
    if (root.dataset.manualTheme) return;
    current = event.matches ? 'dark' : 'light';
    root.setAttribute('data-theme', current);
    sync();
  });

  if (toggle) {
    toggle.addEventListener('click', () => {
      current = current === 'dark' ? 'light' : 'dark';
      root.setAttribute('data-theme', current);
      root.dataset.manualTheme = 'true';
      sync();
    });
  }

  function sync() {
    if (!toggle) return;
    const isDark = current === 'dark';
    toggle.textContent = isDark ? 'Light' : 'Dark';
    toggle.setAttribute('aria-label', 'Switch to ' + (isDark ? 'light' : 'dark') + ' mode');
  }
})();
`;
